Networking312190796_318855038/Models/Users.cs
using System.ComponentModel.DataAnnotations;
namespace Networking312190796_318855038.Models
{
    public class Users
    {
        [Required]
        [StringLength(40, MinimumLength = 3, ErrorMessage = "First name should contain at least 3 characthers")]
        public string FirstName { get; set; }
        [Required]
        [StringLength(40, MinimumLength = 3, ErrorMessage = "Last name should contain at least 3 characthers")]
        public string LastName { get; set; }
        [Key]
        [Required]
        [StringLength(40, MinimumLength = 9, ErrorMessage = "id contain 9 characthers")]
        public string ID { get; set; }
        [Required]
        [RegularExpression("^[0-9]{9}$", ErrorMessage = "Password must contain 9 digits")]
        public string password { get; set; }
        [Required]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage = "Email must contain 9 digits")]
        public string email { get; set; }
        public string role { get; set; }
    }
}

Networking312190796_318855038/Controllers/MoviesController.cs
using Networking312190796_318855038.DalFolder;
using Networking312190796_318855038.Models;
using Networking312190796_318855038.ViewModel;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;

namespace Networking312190796_318855038.Controllers
{
    public class MoviesController : Controller
    {
        public ActionResult addMovie()
        {
            return View("addMovie");
        }
        public ActionResult Submit(Movies tmp)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Dal dal = new Dal();
                    dal.movies.Add(tmp);
                    dal.SaveChanges();
                    Session["Result"] = "Movie Added!";
                }catch (DbUpdateException e)
                         when (e.InnerException?.InnerException is SqlException sqlEx &&
                            (sqlEx.Number == 2601 || sqlEx.Number == 2627))
                {
                        Session["Result"] = "There Was An Error Movie Not Added...";
                }
            }
            return View("addMovie");
        }
        public ActionResult SearchMovie()
        {
            return View("SearchMovie");
        }
        public ActionResult ShowSearch()
        {
            MoviesViewModel mvm = new MoviesViewModel();
            mvm.moviess = new List<Movies>();
            return View("SearchMovie",mvm);
        }
        public ActionResult SearchPriceIncrease()
        {
            Dal dal = new Dal();
            MoviesViewModel mvm = new MoviesViewModel();
            List<Movies> movies = new List<Movies>();
            movies = (from x in dal.movies where x.priceStatus.Contains("NotSale") select x).ToList();
            mvm.moviess = movies;
            return View("ShowSearch", mvm);
        }
        public ActionResult SearchPriceDecrease()
        {
            Dal dal = new Dal();
            MoviesViewModel mvm = new MoviesViewModel();
            List<Movies> movies = new List<Movies>();
            movies = (from x in dal.movies where x.priceStatus.Equals("Sale") select x).ToList();
            mvm.moviess = movies;
            return View("ShowSearch", mvm);
        }
        public ActionResult MostPopular()
        {
            Dal dal = new Dal();
            MoviesViewModel mvm = new MoviesViewModel();
            List<Movies> movies = new List<Movies>();
            movies = (from x in dal.movies where x.Popularity.Equals("Yes") select x).ToList();
            mvm.moviess = movies;
            return View("ShowSearch", mvm);
        }
        public ActionResult SearchMovies()
        {
            Dal dal = new Dal();
            string searchName = Request.Form["Name"].ToString();
            string searchDate = Request.Form["Date"].ToString();
            string searchTime = Request.Form["Hour"].ToString();
            string searchCategory = Request.Form["Category"].ToString();
            MoviesViewModel mvm = new MoviesViewModel();
            List<Movies> movies = new List<Movies>();
            if (searchName != "" && searchDate!= "" && searchTime!= "" && searchCategory != "")
            {
               movies = (from x in dal.movies where x.Name.Contains(searchName) && x.date.ToString().Contains(searchDate) && x.hour.Contains(searchTime) && x.Category.Contains(searchCategory) select x).ToList<Movies>();
            }
            if (searchName != "" && searchDate != "" && searchTime != "")
            {
                movies = (from x in dal.movies where x.Name.Contains(searchName)&& x.date.ToString().Contains(searchDate) && x.hour.Contains(searchTime) select x).ToList<Movies>();
            }
            if (searchName != "" && searchDate != "" && searchCategory != "")
            {
                movies = (from x in dal.movies where x.Name.Contains(searchName) && x.date.ToString().Contains(searchDate) && x.Category.Contains(searchCategory) select x).ToList<Movies>();
            }
            if ( searchDate != "" && searchTime != "" && searchCategory != "")
            {
                movies = (from x in dal.movies where x.date.ToString().Contains(searchDate) && x.hour.Contains(searchTime) && x.Category.Contains(searchCategory) select x).ToList<Movies>();
            }
            if (searchName != "" && searchDate != "")
            {
                movies = (from x in dal.movies where x.Name.Contains(searchName)&& x.date.ToString().Contains(searchDate) select x).ToList<Movies>();
            }
            if (searchName != "" &&  searchTime != "")
            {
                movies = (from x in dal.movies where x.Name.Contains(searchName) && x.hour.Contains(searchTime) select x).ToList<Movies>();
            }
            if (searchName != "" && searchCategory != "")
            {
                movies = (from x in dal.movies where x.Name.Contains(searchName) && x.Category.Contains(searchCategory) select x).ToList<Movies>();
            }
            if (searchDate != "" && searchTime != "")
            {
                movies = (from x in dal.movies where x.date.ToString().Contains(searchDate) && x.hour.Contains(searchTime) select x).ToList<Movies>();
            }
            if (searchDate != "" && searchCategory != "")
            {
                movies = (from x in dal.movies where x.date.ToString().Contains(searchDate) && x.Category.Contains(searchCategory) select x).ToList<Movies>();
            }
            if (searchTime != "" && searchCategory != "")
            {
                movies = (from x in dal.movies where x.hour.Contains(searchTime) && x.Category.Contains(searchCategory) select x).ToList<Movies>();
            }
            if (searchName != "")
            {
                movies = (from x in dal.movies where x.Name.Contains(searchName) select x).ToList<Movies>();
            }
            if (searchDate != "")
            {
                movies = (from x in dal.movies where x.date.ToString().Contains(searchDate) select x).ToList<Movies>();
            }
            if (searchTime != "")
            {
                movies = (from x in dal.movies where x.hour.Contains(searchTime) select x).ToList<Movies>();
            }
            if (searchCategory != "")
            {
                movies = (from x in dal.movies where x.Category.Contains(searchCategory) select x).ToList<Movies>();
            }
            mvm.moviess = movies;
            return View("ShowSearch", mvm);
        }
        public ActionResult MoviesGallery()
        {
            Dal dal = new Dal();
            List<Movies> movies = (from x in dal.movies select x).ToList<Movies>();
            MoviesViewModel mvm = new MoviesViewModel();
            mvm.moviess = movies;
            return View("MoviesGallery", mvm);
        }
        public ActionResult RemoveMovie()
        {
            return View("RemoveMovie");
        }
        public ActionResult Remove()
        {
            string searchName = Request.Form["Name"].ToString();
            string searchDate = Request.Form["Date"].ToString();
            string searchTime = Request.Form["Hour"].ToString();
            string searchHall = Request.Form["HallNum"].ToString();
            Dal dal = new Dal();
            List<Movies> movies = (from x in dal.movies where x.Name.Equals(searchName) && x.hour.Equals(searchTime) && x.date.Equals(searchDate) && x.HallNum.Equals(searchHall) select x).ToList<Movies>();
            if(movies.Count==1)
            {
                dal.movies.Remove(movies[0]);
                dal.SaveChanges();
                Session["Result"] = "Movie Removed!";
            }
            else
            {
                Session["Result"] = "No Movie Removed!";
            }
            return View("RemoveMovie");
        }
    }
}

Networking312190796_318855038/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Web.Mvc;
using Networking312190796_318855038.DalFolder;
using Networking312190796_318855038.Models;

namespace Networking312190796_318855038.Controllers
{
    public class TicketsController : Controller
    {
        public static List<Tickets> ticketxss=new List<Tickets>();
        public static Tickets tmp=new Tickets();
        // GET: Admin
        public ActionResult BuyTicket(string name,string dates,string hours,string HallNums)
        {
            tmp.Name = name;
            tmp.date = dates;
            tmp.hour = hours;
            tmp.HallNum = HallNums;
            Session["name"] = name;
            Session["Date"] = dates;
            Session["Hour"] = hours;
            Session["Hallnum"] = HallNums;
            return View("BuyTicket");
        }
        public ActionResult Submit()
        {
            Tickets.number++;
            tmp.ticketnum = Tickets.number.ToString();
            tmp.row = Request.Form["Row"].ToString();
            tmp.seat = Request.Form["Seat"].ToString();
            if (ModelState.IsValid)
            {
                try
                {
                    Dal dal = new Dal();
                    dal.tickets.Add(tmp);
                    dal.SaveChanges();
                    Session["Result"] = "Your Purchase Completed!";
                }
                catch (DbUpdateException e)
                         when (e.InnerException?.InnerException is SqlException sqlEx &&
                            (sqlEx.Number == 2601 || sqlEx.Number == 2627))
            {
                Session["Result"] = "There Was An Error Ticket Purchase Not Completed!...";
            }
        }
            return View("BuyTicket");
        }
        public ActionResult addToCart(string name, string dates, string hours, string HallNums)
        {
            Tickets.number++;
            tmp.ticketnum = Tickets.number.ToString();
            tmp.row = Request.Form["Row"].ToString();
            tmp.seat = Request.Form["Seat"].ToString();
            Tickets tmp1 = new Tickets();
            tmp1.Name = tmp.Name;
            tmp1.date = tmp.date;
            tmp1.hour = tmp.hour;
            tmp1.HallNum = tmp.HallNum;
            tmp1.ticketnum = tmp.ticketnum;
            tmp1.row = tmp.row;
            tmp1.seat = tmp.seat;
            if (Session["login"] != null)
            {
                ticketxss.Add(tmp1);
                Session["status"] = "Ticket add to your Cart";
                return View("../Users/HomePage");
            }
            else
            {
                Session["status"] = "You need to login before insert ticket to the shoping cart";
            }
            return View("BuyTicket");
        }
        public ActionResult Remove(string name, string dates, string hours, string HallNums)
        {
            for(int i=0;i<ticketxss.Count;i++)
            {
                if(ticketxss[i].Name.Equals(name)&&ticketxss[i].date.Equals(dates)&&ticketxss[i].hour.Equals(hours)&&ticketxss[i].HallNum.Equals(HallNums))
                {
                    ticketxss.Remove(ticketxss[i]);
                }
            }
            return View("../Users/ShopingCart");
        }
    }
}

Networking312190796_318855038/Controllers/UsersController.cs
using Networking312190796_318855038.DalFolder;
using Networking312190796_318855038.Models;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Web.Mvc;

namespace Networking312190796_318855038.Controllers
{
    public class UsersController : Controller
    {
        // GET: Users
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Signup()
        {
            return View("Signup");
        }
        public ActionResult HomePage()
        {
            return View("HomePage");
        }
        public ActionResult Submit(Users tmp)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    tmp.role = "User";
                    Dal dal = new Dal();
                    dal.users.Add(tmp);
                    dal.SaveChanges();
                    Session["Result"] = "Register Complete!";
                }
                catch (DbUpdateException e)
                        when (e.InnerException?.InnerException is SqlException sqlEx &&
                           (sqlEx.Number == 2601 || sqlEx.Number == 2627))
                {
                    Session["Result"] = "There Was An Error try To Sign Up Agian!...";
                }
            }
            return View("../Home/index");
        }
        public ActionResult ShopingCart()
        {
            return View("ShopingCart");
        }
    }
}

Networking312190796_318855038/Views/Users/HomePage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cinema Sami</title>
    <style>
        .button {
            border-radius: 4px;
            background-color: #f4511e;
            border: none;
            color: #FFFFFF;
            text-align: center;
            font-size: 28px;
            padding: 20px;
            width: 200px;
            transition: all 0.5s;
            cursor: pointer;
            margin: 5px;
            font: italic small-caps bold 16px/2 cursive;
        }
    </style>
</head>
<body style="background-image: url('https://i2.wp.com/maryfarmarpta.org/wp-content/uploads/2019/03/popcorn1.jpg?resize=600%2C559&ssl=1'); background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;">
    <div style="position: relative; width: 0; height: 0">
        <div style="position: absolute; left: 100px; top: 50px">
            <input id="Button1" type="button" value="Movies Gallery" class="button" onclick="location.href='@Url.Action("MoviesGallery", "Movies")' ">
        </div>
        <div style="position: absolute; left: 350px; top: 50px">
            <input id="Button4" type="button" class="button" value="Shoping Cart" onclick="location.href='@Url.Action("ShopingCart", "Users")' " />
        </div>
        <div style="position: absolute; left: 600px; top: 50px">
            <input id="Button4" type="button" class="button" value="About us" />
        </div>
    </div>
    <div style="position: absolute; left: 400px; top: 400px">
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Koral Moyal 318855038 Nave Shelly 312190796</p>
        </footer>
    </div>
</body>
</html>

Networking312190796_318855038/Views/Users/ShopingCart.cshtml
@model Networking312190796_318855038.ViewModel.MoviesViewModel
@using Networking312190796_318855038.Controllers
@{
    ViewBag.Title = "showsearch";
}
<!DOCTYPE html>
<html>
<title>Search Movie</title>
<head>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
            font: italic small-caps bold 16px/2 cursive;
        }
        th, td {
            text-align: left;
            padding: 8px;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2
        }
        tr:nth-child(odd) {
            background-color: #f2f2f2
        }
        th {
            background-color: #f4511e;
            color: white;
        }
        .button {
            border-radius: 4px;
            background-color: #f4511e;
            border: none;
            color: #FFFFFF;
            text-align: center;
            font-size: 16px;
            font: italic small-caps bold 16px/2 cursive;
            padding: 15px 32px;
            transition: all 0.5s;
            cursor: pointer;
            margin: 4px 2px;
        }
        .p2 {
            font: italic small-caps bold 16px/2 cursive;
        }
    </style>
    <meta name="viewport" content="width=device-width" />
    <title>SearchMovie</title>
</head>
<body style="background-image: url('https://i2.wp.com/maryfarmarpta.org/wp-content/uploads/2019/03/popcorn1.jpg?resize=600%2C559&ssl=1'); background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;">
    </br>
    <p class="p2"> Search results:</p>
    </br>
    <table style="width:100%">
        <tr>
            <th>Name</th>
            <th>seat</th>
            <th>row</th>
            <th>date</th>
            <th>hour</th>
            <th>HallNum</th>
            <th> </th>
            <th> </th>
        </tr>
        @foreach (var ticket in TicketsController.ticketxss)
        {
    <tr>
        <td>@ticket.Name</td>
        <td>@ticket.seat</td>
        <td>@ticket.row</td>
        <td>@ticket.date</td>
        <td>@ticket.hour</td>
        <td>@ticket.HallNum</td>
        <td><input type='button' class="button" value='Buy Ticket' onclick="location.href='@Url.Action("BuyTicket", "Tickets",new {name = @ticket.Name,dates=@ticket.date,hours=@ticket.hour,HallNums=@ticket.HallNum })'" /></td>
        <td><input type='button' class="button" value='Remove Ticket' onclick="location.href='@Url.Action("Remove", "Tickets",new {name = @ticket.Name,dates=@ticket.date,hours=@ticket.hour,HallNums=@ticket.HallNum })'" /></td>
    </tr>
        }
    </table>
</body>
</html>

Networking312190796_318855038/Views/Users/Signup.cshtml
@model Networking312190796_318855038.Models.Users

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>
    <style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 60px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
}

hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Add padding to container elements */
.container {
  padding: 16px;
}

/* Clear floats */
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}
     .p2 {
            font: italic small-caps bold 16px/2 cursive;
        }
          .p3 {
            font: italic small-caps bold 16px/2 cursive;
            font-size: 30px;
        }
          .button {
  border-radius: 4px;
  background-color: #f4511e;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 28px;
  padding: 20px;
  width: 200px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
    font: italic small-caps bold 16px/2 cursive;
}
    </style>
</head>
<body style="background-image: url('https://i2.wp.com/maryfarmarpta.org/wp-content/uploads/2019/03/popcorn1.jpg?resize=600%2C559&ssl=1'); background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;">

    <div class="row">
        <div class="col-75">
            <div class="container">
                <p class="p3"> Sign Up</p>
                <p class="p2"> Please fill your details to create an account</p>
                <p class="p2"> @Session["Result"]</p>
                @using (Html.BeginForm("Submit", "Users", FormMethod.Post))
                {
                    <b>first Name</b>
                    <br>
                    @Html.TextBoxFor(m => m.FirstName) @Html.ValidationMessageFor(x => x.FirstName)
                    <br>
                    <b>Last Name</b>
                    <br>
                    @Html.TextBoxFor(m => m.LastName) @Html.ValidationMessageFor(x => x.LastName)
                    <br>
                    <b>ID</b>
                    <br>
                    @Html.TextBoxFor(m => m.ID) @Html.ValidationMessageFor(x => x.ID)
                    <br>
                    <b>password</b>
                    <br>
                    @Html.TextBoxFor(m => m.password) @Html.ValidationMessageFor(x => x.password)
                    <br>
                    <b>Email</b>
                    <br>
                    @Html.TextBoxFor(m => m.email) @Html.ValidationMessageFor(x => x.email)
                    <br>
                    <input id="Submit1" type="submit" value="SIGN ME UP" class="button" />
                }
            </div>
        </div>
    </div>

</body>
</html>